Document: svn2dch
Title: Debian svn2dch Manual
Author: <insert document author here>
Abstract: This manual describes what svn2dch is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/svn2dch/svn2dch.sgml.gz

Format: postscript
Files: /usr/share/doc/svn2dch/svn2dch.ps.gz

Format: text
Files: /usr/share/doc/svn2dch/svn2dch.text.gz

Format: HTML
Index: /usr/share/doc/svn2dch/html/index.html
Files: /usr/share/doc/svn2dch/html/*.html
